import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blogs",
  description: "Generated by create next app",

  openGraph: {
    title: "Notcodesid",
    description: "Exploring code, sharing knowledge, and building the future.",
    url: "https://sidblogs.vercel.app/",
    siteName: "notcodesid",
    images: [{ url: "https://sidblogs.vercel.app/x-pfp.png", width: 1200, height: 630 }],
    locale: "en-IN",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        </body>
    </html>
  );
}
