name = "bloggingapp"
compatibility_date = "2024-08-27"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTU0NmQxOTItMWQwMC00YWRhLTg4MWItM2NiMWVkY2U0MDA2IiwidGVuYW50X2lkIjoiODdlMWMxMGE4ZTNmZWVmMDFhODhjNjNmMTZjMjQzMjc5NGE4ZGY5NDUxNDk1MmUxNWZjODJmY2QxOWZjNjI4MSIsImludGVybmFsX3NlY3JldCI6IjU3MjcwNjMzLTcyZjEtNDg3MC1iODliLTE4ZTZjMzdjMmVlMSJ9.zyy0vQSL-B_EvvY_wbWsaA_Y7s7c9YdeTau7gOozYv0"



MY_VAR = "my-variable"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"